export default {
  nl: {
    title: 'Jouw berichten',
    searchInMessages: 'Zoeken in berichten',
    search: 'Zoek',
    nameChangeMessage: 'Gebruiker \'@old_name\' heeft zijn naam veranderd naar  \'@new_name\'.',
    mentorChangeLeaveMessage: 'Beste mentor, ik ben niet langer je student, maar ben de cursus \'@course\' gaan volgen bij een andere mentor.  Mijn nieuwe mentor zal ook de lessen nakijken die eventueel nog niet waren nagekeken.',
    mentorChangeEnter: 'Beste mentor, ik ben nu begonnen aan de cursus \'@course\', ik ben deze cursus al eerder gestart bij een andere mentor. Mochten er nog lessen niet nagekeken zijn, zou die je dan willen nakijken?',
    studentEnrollment: 'Ik ben nu begonnen aan de cursus \'@course\'.',
    studentLessonSubmission: 'Beste mentor, @url op les \'@lesson\' van cursus \'@course\'.',
    studentLessonSubmissionLabel: 'hier zijn mijn antwoorden',
    mentorLessonSubmissionReview: 'Beste student, @url \'@lesson\' van cursus \'@course\'.  Eventuele reacties op je antwoorden vind je in de berichtjes hierna.',
    mentorLessonSubmissionReviewLabel: 'hierbij de nagekeken les',
    question: 'Vraag:',
    answer: 'Gegeven antwoord:',
    correct: 'Correcte antwoord:',
    review: 'Reactie mentor',
    true: 'Juist',
    false: 'Onjuist',
    send: 'Verstuur',
    dashboard: 'Dashboard',
    noChannel: 'Aangezien je nog geen cursus met een mentor hebt gevolgd, zijn er nog geen verstuurde berichten om weer te geven.',
    groupName: 'Groepsnaam',
    cancel: 'Annuleren',
    close: 'Sluiten',
    channel: 'Groep: ',
    groupSaved: 'Chat groep is opgeslagen',
    groupSaveFailed: 'Er is een fout opgetreden tijdens het opslaan van de instellingen van de chatgroep. Probeert u het opnieuw of neem contact op met de ondersteuning voor verdere hulp.',
    groupDelete: 'Bent u zeker dat u deze groep wilt verwijderen? Hiermee worden ook alle bijbehorende berichten permanent verwijderd.',
    delete: 'Verwijderen',
    groupDeleted: 'De groep en alle berichten in de groep zijn verwijderd.',
    groupDeletionFailed: 'Er is een fout opgetreden tijdens het verwijderen van de chatgroep. Probeert u het opnieuw of neem contact op met de ondersteuning voor verdere hulp.'
  }
};
