export default {
  nl: {
    title: 'Jouw berichten',
    searchInMessages: 'Zoeken in berichten',
    search: 'Zoek',
    nameChangeMessage: 'Gebruiker \'@old_name\' heeft zijn naam veranderd naar  \'@new_name\'.',
    mentorChangeLeaveMessage: 'Beste mentor, ik ben niet langer je student, maar ben de cursus \'@course\' gaan volgen bij een andere mentor.  Mijn nieuwe mentor zal ook de lessen nakijken die eventueel nog niet waren nagekeken.',
    mentorChangeEnter: 'Beste mentor, ik ben nu begonnen aan de cursus \'@course\', ik ben deze cursus al eerder gestart bij een andere mentor. Mochten er nog lessen niet nagekeken zijn, zou die je dan willen nakijken?',
    studentEnrollment: 'Ik ben nu begonnen aan de cursus \'@course\'.',
    studentLessonSubmission: 'Beste mentor, @url op les \'@lesson\' van cursus \'@course\'.',
    studentLessonSubmissionLabel: 'hier zijn mijn antwoorden',
    mentorLessonSubmissionReview: 'Beste student, @url \'@lesson\' van cursus \'@course\'.  Eventuele reacties op je antwoorden vind je in de berichtjes hierna.',
    mentorLessonSubmissionReviewLabel: 'hierbij de nagekeken les',
    question: 'Vraag:',
    answer: 'Gegeven antwoord:',
    correct: 'Correcte antwoord:',
    review: 'Reactie mentor',
    true: 'Juist',
    false: 'Onjuist',
    send: 'Verstuur',
    dashboard: 'Dashboard',
    noChannel: 'Aangezien je nog geen cursus met een mentor hebt gevolgd, zijn er nog geen verstuurde berichten om weer te geven.',
    groupName: 'Groepsnaam',
    cancel: 'Annuleren',
    close: 'Sluiten',
    channel: 'Groep: ',
    groupSaved: 'Chat groep is opgeslagen',
    groupSaveFailed: 'Er is een fout opgetreden tijdens het opslaan van de instellingen van de chatgroep. Probeert u het opnieuw of neem contact op met de ondersteuning voor verdere hulp.',
    groupDelete: 'Bent u zeker dat u deze groep wilt verwijderen? Hiermee worden ook alle bijbehorende berichten permanent verwijderd.',
    delete: 'Verwijderen',
    groupDeleted: 'De groep en alle berichten in de groep zijn verwijderd.',
    groupDeletionFailed: 'Er is een fout opgetreden tijdens het verwijderen van de chatgroep. Probeert u het opnieuw of neem contact op met de ondersteuning voor verdere hulp.'
  },
  en: {
    title: 'Your messages',
    searchInMessages: 'Search in messages',
    search: 'Search',
    nameChangeMessage: 'User \'@old_name\' has changed their name to \'@new_name\'.',
    mentorChangeLeaveMessage: 'Dear mentor, I am no longer your student, but have chosen to take the course \'@course\' with another mentor. My new mentor will also review any lessons that may not have been reviewed yet.',
    mentorChangeEnter: 'Dear mentor, I have now started the course \'@course\'. I had previously started this course with another mentor. If there are any lessons that have not yet been reviewed, could you please review them?',
    studentEnrollment: 'I have now started the course \'@course\'.',
    studentLessonSubmission: 'Dear mentor, @url on lesson \'@lesson\' of course \'@course\'.',
    studentLessonSubmissionLabel: 'here are my answers',
    mentorLessonSubmissionReview: 'Dear student, @url \'@lesson\' of course \'@course\'. Any feedback on your answers can be found in the messages below.',
    mentorLessonSubmissionReviewLabel: 'here is the reviewed lesson',
    question: 'Question:',
    answer: 'Given answer:',
    correct: 'Correct answer:',
    review: 'Mentor’s feedback',
    true: 'True',
    false: 'False',
    send: 'Send',
    dashboard: 'Dashboard',
    noChannel: 'Since you have not yet followed a course with a mentor, there are no sent messages to display.',
    groupName: 'Group name',
    cancel: 'Cancel',
    close: 'Close',
    channel: 'Group: ',
    groupSaved: 'Chat group has been saved',
    groupSaveFailed: 'An error occurred while saving the chat group settings. Please try again or contact support for further assistance.',
    groupDelete: 'Are you sure you want to delete this group? This will also permanently delete all associated messages.',
    delete: 'Delete',
    groupDeleted: 'The group and all messages in the group have been deleted.',
    groupDeletionFailed: 'An error occurred while deleting the chat group. Please try again or contact support for further assistance.'
  }
};
